### ISSUE TITLE
stack pointer init

### ISSUE THREAD

**Issue by zmajcenic** [turbor/msxblockpuzzle#2]
Hi,

I believe you should remove stack pointer initialization because:
1. Your code calls previous H.TIMI routine which can easily be disk rom/Nextor
2. SP is placed within structures of disk routines
3. I think that my previous bug report was the real reason of lockups 

Thanks

**Comment by turbor** [comment]
That stack pointer initialization  was an attempted quick-fix (that turned out to be unsuccessful ) 
And since there was no way to exit the game it was thought to be a non-issue if it mangled existing data.

I will remove the SP init code as per your suggestion.
